# Generated by Django 4.2 on 2023-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagament',
            fields=[
                ('idPagament', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nTargeta', models.IntegerField()),
                ('dataTargeta', models.DateField()),
                ('cvc', models.IntegerField(max_length=3)),
            ],
        ),
    ]
