# Generated by Django 4.2 on 2023-05-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carreto',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
        migrations.AlterField(
            model_name='carreto',
            name='idCarreto',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
