# Generated by Django 4.2 on 2023-05-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0004_carreto_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='nomCarreto',
        ),
    ]
