# Generated by Django 4.2 on 2023-05-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0005_remove_carreto_nomcarreto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='user',
        ),
        migrations.AddField(
            model_name='carreto',
            name='esComprat',
            field=models.BooleanField(default=False),
        ),
    ]
