# Generated by Django 4.2 on 2023-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreto', '0005_remove_carreto_nomcarreto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('idComanda', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('esComprat', models.BooleanField(default=False)),
                ('carretons', models.ManyToManyField(to='carreto.carreto')),
            ],
        ),
    ]
