# Generated by Django 4.2 on 2023-05-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
