# Generated by Django 4.2 on 2023-05-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comandes', '0002_comanda_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='esComprat',
        ),
    ]
