# Generated by Django 4.2 on 2023-05-16 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('comandes', '0003_remove_comanda_escomprat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
