# Generated by Django 4.2 on 2023-05-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('userNick', models.CharField(max_length=12, verbose_name='userNick')),
            ],
        ),
    ]
