# Generated by Django 4.2 on 2023-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producte',
            fields=[
                ('idProducte', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nom', models.IntegerField()),
                ('preu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabricant', models.CharField(max_length=50, verbose_name='fabricant')),
                ('origen', models.CharField(max_length=50, verbose_name='fabricant')),
                ('caducitat', models.DateField()),
                ('descripcio', models.TextField()),
            ],
        ),
    ]
